name: fuot_shop
description: "Fuot Shop - Cửa hàng đồ phượt cho dân mê xe máy"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2

  # Utils
  intl: ^0.19.0
  csv: ^6.0.0
  file_picker: ^8.1.6
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  firebase_storage: ^12.4.10
  desktop_drop: ^0.7.0
  super_clipboard: ^0.9.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
